# Generated by Django 4.1.3 on 2023-01-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('pay', models.CharField(max_length=100)),
                ('bids', models.IntegerField()),
                ('is_it_done', models.BooleanField(default=False)),
            ],
        ),
    ]
