# Generated by Django 4.1.3 on 2023-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='pay',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
