# Generated by Django 4.1.3 on 2023-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_creator_alter_project_bids_alter_project_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=None),
        ),
    ]
