# Generated by Django 4.1.3 on 2023-02-10 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_rename_pay_project_payment_remove_project_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='candidates',
            field=models.ManyToManyField(related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
