# Generated by Django 4.1.3 on 2023-02-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_application_alter_project_candidates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='candidates',
            new_name='applications',
        ),
    ]
