# Generated by Django 4.1.3 on 2023-02-12 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_candidates_project_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
