# Generated by Django 4.1.3 on 2023-02-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_application_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
