# Generated by Django 4.1.3 on 2023-02-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_application_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
