# Generated by Django 4.1.3 on 2023-02-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_application_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_it_paid',
            field=models.BooleanField(default=False),
        ),
    ]
