# Generated by Django 4.1.3 on 2023-02-20 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_project_is_it_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applications',
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='applications',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='apllications', to='projects.application'),
            preserve_default=False,
        ),
    ]
