# Generated by Django 4.1.3 on 2023-02-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applications',
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project'),
        ),
    ]
