# Generated by Django 4.1.3 on 2023-02-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_project_applications_application_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='LV', max_length=5),
            preserve_default=False,
        ),
    ]
