# Generated by Django 4.1.3 on 2023-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_type_hourly',
            field=models.BooleanField(default=False),
        ),
    ]
