# Generated by Django 4.1.3 on 2023-02-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_payment_type_hourly'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='currency',
            field=models.CharField(default='BGN', max_length=5),
            preserve_default=False,
        ),
    ]
