# Generated by Django 4.1.3 on 2023-02-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_application_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bid',
            field=models.IntegerField(),
        ),
    ]
