# Generated by Django 4.1.3 on 2023-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client'), ('teamleader', 'Team Leader')], default='freelancer', max_length=15),
        ),
    ]
