# Generated by Django 4.1.3 on 2023-02-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0002_cv_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='last_name',
        ),
    ]
