# Generated by Django 4.1.3 on 2023-02-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0003_remove_cv_first_name_remove_cv_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experiences',
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(default='Python'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
