# Generated by Django 4.1.3 on 2023-02-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0004_remove_cv_education_remove_cv_experiences_cv_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='file',
            field=models.FileField(default='CV.txt', upload_to=''),
            preserve_default=False,
        ),
    ]
